# Generated by Django 3.0.6 on 2020-06-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60, unique=True)),
                ('firstname', models.CharField(default=False, max_length=60)),
                ('lastname', models.CharField(default=False, max_length=60)),
                ('password', models.CharField(default=False, max_length=60)),
                ('timezone', models.CharField(default=False, max_length=60)),
                ('language', models.CharField(default=False, max_length=60)),
            ],
        ),
    ]
