# Generated by Django 3.0.6 on 2020-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='industry',
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default=False, max_length=60),
        ),
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(default=False, max_length=60),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default=False, max_length=60),
        ),
        migrations.AddField(
            model_name='users',
            name='timezone',
            field=models.CharField(default=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default=False, max_length=60),
        ),
    ]
